<?php

declare(strict_types=1);

namespace ModerationAPI\Content\ContentSubmitResponse;

use ModerationAPI\Content\ContentSubmitResponse\Content\Modified;
use ModerationAPI\Content\ContentSubmitResponse\Content\Modified\ModifiedNestedObjectContent\Audio;
use ModerationAPI\Content\ContentSubmitResponse\Content\Modified\ModifiedNestedObjectContent\Image;
use ModerationAPI\Content\ContentSubmitResponse\Content\Modified\ModifiedNestedObjectContent\Text;
use ModerationAPI\Content\ContentSubmitResponse\Content\Modified\ModifiedNestedObjectContent\Video;
use ModerationAPI\Core\Attributes\Required;
use ModerationAPI\Core\Concerns\SdkModel;
use ModerationAPI\Core\Contracts\BaseModel;

/**
 * Potentially modified content.
 *
 * @phpstan-type ContentShape = array{
 *   id: string,
 *   masked: bool,
 *   modified: string|null|array<string,mixed>|array<string,Text|Image|Video|Audio>,
 * }
 */
final class Content implements BaseModel
{
    /** @use SdkModel<ContentShape> */
    use SdkModel;

    /**
     * The unique identifier for the content. Either the contentId provided by you or an autogenerated ID.
     */
    #[Required]
    public string $id;

    /**
     * Whether any values have been masked.
     */
    #[Required]
    public bool $masked;

    /**
     * The modified content, if any.
     *
     * @var string|array<string,mixed>|array<string,Text|Image|Video|Audio>|null $modified
     */
    #[Required(union: Modified::class)]
    public string|array|null $modified;

    /**
     * `new Content()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * Content::with(id: ..., masked: ..., modified: ...)
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new Content)->withID(...)->withMasked(...)->withModified(...)
     * ```
     */
    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     *
     * @param string|array<string,mixed>|array<string,Text|array{
     *   text: string, type: 'text'
     * }|Image|array{type: 'image', url: string}|Video|array{
     *   type: 'video', url: string
     * }|Audio|array{type: 'audio', url: string}>|null $modified
     */
    public static function with(
        string $id,
        bool $masked,
        string|array|null $modified
    ): self {
        $obj = new self;

        $obj['id'] = $id;
        $obj['masked'] = $masked;
        $obj['modified'] = $modified;

        return $obj;
    }

    /**
     * The unique identifier for the content. Either the contentId provided by you or an autogenerated ID.
     */
    public function withID(string $id): self
    {
        $obj = clone $this;
        $obj['id'] = $id;

        return $obj;
    }

    /**
     * Whether any values have been masked.
     */
    public function withMasked(bool $masked): self
    {
        $obj = clone $this;
        $obj['masked'] = $masked;

        return $obj;
    }

    /**
     * The modified content, if any.
     *
     * @param string|array<string,mixed>|array<string,Text|array{
     *   text: string, type: 'text'
     * }|Image|array{type: 'image', url: string}|Video|array{
     *   type: 'video', url: string
     * }|Audio|array{type: 'audio', url: string}>|null $modified
     */
    public function withModified(string|array|null $modified): self
    {
        $obj = clone $this;
        $obj['modified'] = $modified;

        return $obj;
    }
}
