<?php

declare(strict_types=1);

namespace ModerationAPI\Content\ContentSubmitResponse;

use ModerationAPI\Content\ContentSubmitResponse\Content\Modified;
use ModerationAPI\Core\Attributes\Optional;
use ModerationAPI\Core\Attributes\Required;
use ModerationAPI\Core\Concerns\SdkModel;
use ModerationAPI\Core\Contracts\BaseModel;

/**
 * Potentially modified content.
 *
 * @phpstan-import-type ModifiedVariants from \ModerationAPI\Content\ContentSubmitResponse\Content\Modified
 * @phpstan-import-type ModifiedShape from \ModerationAPI\Content\ContentSubmitResponse\Content\Modified
 *
 * @phpstan-type ContentShape = array{
 *   id: string,
 *   masked: bool,
 *   modified: ModifiedShape|null,
 *   transcript?: string|null,
 * }
 */
final class Content implements BaseModel
{
    /** @use SdkModel<ContentShape> */
    use SdkModel;

    /**
     * The unique identifier for the content. Either the contentId provided by you or an autogenerated ID.
     */
    #[Required]
    public string $id;

    /**
     * Whether any values have been masked.
     */
    #[Required]
    public bool $masked;

    /**
     * The modified content, if any.
     *
     * @var ModifiedVariants|null $modified
     */
    #[Required(union: Modified::class)]
    public string|array|null $modified;

    /**
     * The transcribed text from audio content. Only present when audio moderation is used and transcript inclusion is enabled on the channel.
     */
    #[Optional(nullable: true)]
    public ?string $transcript;

    /**
     * `new Content()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * Content::with(id: ..., masked: ..., modified: ...)
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new Content)->withID(...)->withMasked(...)->withModified(...)
     * ```
     */
    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     *
     * @param ModifiedShape|null $modified
     */
    public static function with(
        string $id,
        bool $masked,
        string|array|null $modified,
        ?string $transcript = null,
    ): self {
        $self = new self;

        $self['id'] = $id;
        $self['masked'] = $masked;
        $self['modified'] = $modified;

        null !== $transcript && $self['transcript'] = $transcript;

        return $self;
    }

    /**
     * The unique identifier for the content. Either the contentId provided by you or an autogenerated ID.
     */
    public function withID(string $id): self
    {
        $self = clone $this;
        $self['id'] = $id;

        return $self;
    }

    /**
     * Whether any values have been masked.
     */
    public function withMasked(bool $masked): self
    {
        $self = clone $this;
        $self['masked'] = $masked;

        return $self;
    }

    /**
     * The modified content, if any.
     *
     * @param ModifiedShape|null $modified
     */
    public function withModified(string|array|null $modified): self
    {
        $self = clone $this;
        $self['modified'] = $modified;

        return $self;
    }

    /**
     * The transcribed text from audio content. Only present when audio moderation is used and transcript inclusion is enabled on the channel.
     */
    public function withTranscript(?string $transcript): self
    {
        $self = clone $this;
        $self['transcript'] = $transcript;

        return $self;
    }
}
